name: busycards
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.5+25

environment:
  sdk: ">=2.17.3 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  sqflite: ^2.0.2
  path: ^1.7.0
  provider: ^6.0.2
  just_audio: ^0.9.33
  url_launcher: ^6.1.2
  shared_preferences: ^2.0.13
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/busycard/table0/icon/
    - assets/busycard/table0/image/
    - assets/busycard/table0/audio/
    - assets/busycard/table0/raw/
    - assets/busycard/table1/icon/
    - assets/busycard/table1/image/
    - assets/busycard/table1/audio/
    - assets/busycard/table1/raw/
    - assets/busycard/table2/icon/
    - assets/busycard/table2/image/
    - assets/busycard/table2/audio/
    - assets/busycard/table2/raw/
    - assets/busycard/table3/icon/
    - assets/busycard/table3/image/
    - assets/busycard/table3/audio/
    - assets/busycard/table3/raw/
    - assets/busycard/table4/icon/
    - assets/busycard/table4/image/
    - assets/busycard/table4/audio/
    - assets/busycard/table4/raw/
    - assets/busycard/table5/icon/
    - assets/busycard/table5/image/
    - assets/busycard/table5/audio/
    - assets/busycard/table5/raw/
    - assets/busycard/table6/icon/
    - assets/busycard/table6/image/
    - assets/busycard/table6/audio/
    - assets/busycard/table6/raw/
    - assets/busycard/table7/icon/
    - assets/busycard/table7/image/
    - assets/busycard/table7/audio/
    - assets/busycard/table7/raw/
    - assets/busycard/table8/icon/
    - assets/busycard/table8/image/
    - assets/busycard/table8/audio/
    - assets/busycard/table8/raw/
    - assets/busycard/table9/icon/
    - assets/busycard/table9/image/
    - assets/busycard/table9/audio/
    - assets/busycard/table9/raw/
    - assets/busycard/table10/icon/
    - assets/busycard/table10/image/
    - assets/busycard/table10/audio/
    - assets/busycard/table10/raw/
    - assets/busycard/table11/icon/
    - assets/busycard/table11/image/
    - assets/busycard/table11/audio/
    - assets/busycard/table11/raw/
    - assets/busycard/table12/icon/
    - assets/busycard/table12/image/
    - assets/busycard/table12/audio/
    - assets/busycard/table12/raw/
    - assets/busycard/table13/icon/
    - assets/busycard/table13/image/
    - assets/busycard/table13/audio/
    - assets/busycard/table13/raw/
    - assets/busycard/table14/icon/
    - assets/busycard/table14/image/
    - assets/busycard/table14/audio/
    - assets/busycard/table14/raw/
    - assets/busycard/table15/icon/
    - assets/busycard/table15/image/
    - assets/busycard/table15/audio/
    - assets/busycard/table15/raw/
    - assets/busycard/table16/icon/
    - assets/busycard/table16/image/
    - assets/busycard/table16/audio/
    - assets/busycard/table16/raw/
    - assets/busycard/table17/icon/
    - assets/busycard/table17/image/
    - assets/busycard/table17/audio/
    - assets/busycard/table17/raw/
    - assets/busycard/table18/icon/
    - assets/busycard/table18/image/
    - assets/busycard/table18/audio/
    - assets/busycard/table18/raw/
    - assets/busycard/table19/icon/
    - assets/busycard/table19/image/
    - assets/busycard/table19/audio/
    - assets/busycard/table19/raw/
    - assets/busycard/table20/icon/
    - assets/busycard/table20/image/
    - assets/busycard/table20/audio/
    - assets/busycard/table20/raw/
    - assets/busycard/table21/icon/
    - assets/busycard/table21/image/
    - assets/busycard/table21/audio/
    - assets/busycard/table21/raw/
    - assets/busycard/table22/icon/
    - assets/busycard/table22/image/
    - assets/busycard/table22/audio/
    - assets/busycard/table22/raw/
    - assets/busycard/menu/audio/
    - assets/busycard/menu/icon/
    - assets/game/audio/no/
    - assets/game/audio/yes/
    - assets/game/audio/question/
    - assets/game/audio/answer/
    - assets/game/image/
    - assets/db/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
