name: busycards
description: A new Flutter project.
publish_to: 'none'
version: 2.0.14+38

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.1
  intl: ^0.19.0
  path: ^1.9.0
  flutter_launcher_icons: ^0.14.1
  provider: ^6.1.2
  url_launcher: ^6.3.1
  mobx: ^2.4.0
  flutter_mobx: ^2.2.1+1
  get_it: ^8.0.2
  go_router: ^14.6.0
  flutter_svg: ^2.0.14
  shared_preferences: ^2.3.3
  flutter_native_splash: ^2.4.3
  audioplayers: ^6.1.0
  
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  mobx_codegen: ^2.6.2

flutter:
  uses-material-design: true
  assets:
    - assets/babycards/cards/icons/
    - assets/babycards/cards/images/
    - assets/babycards/cards/audios/ru/
    - assets/babycards/cards/raws/default/
    - assets/babycards/cards/raws/ru/
    - assets/babycards/categories/icons/
    - assets/babycards/categories/audios/ru/
    - assets/database/
    - assets/app/audios/
    - assets/app/icons/
    - assets/app/images/
    - assets/games/audios/answers/ru/
    - assets/games/audios/questions/ru/

flutter_launcher_icons:
  android: true
  image_path_android: 'assets/app/icons/icon_app.png'
  ios: true
  image_path_ios: 'assets/app/icons/icon_app.png'
  remove_alpha_ios: true
  min_sdk_android: 21
  adaptive_icon_background: '#00B2FF'

flutter_native_splash:
  color: '#ffffff'
  image: assets/app/icons/icon_splash.png
  android_12:
    color: '#ffffff'
    image: assets/app/icons/icon_splash.png
  web: false
