name: busycards
description: A new Flutter project.
publish_to: 'none'
version: 2.0.5+25

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3
  path: ^1.9.0
  provider: ^6.1.2
  assets_audio_player: ^3.1.1
  url_launcher: ^6.2.6
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  get_it: ^7.7.0
  go_router: ^14.0.2
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.9
  mobx_codegen: ^2.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/cards/audio/
    - assets/cards/icon/
    - assets/cards/image/
    - assets/cards/raw/
    - assets/db/
    - assets/games/audio/answers/
    - assets/games/audio/correctly/
    - assets/games/audio/questions/
    - assets/images/
    - assets/icons/

