name: busycards
description: A new Flutter project.
publish_to: 'none'
version: 2.0.12+5

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3
  intl: ^0.19.0
  path: ^1.9.0
  flutter_launcher_icons: ^0.14.1
  provider: ^6.1.2
  url_launcher: ^6.2.6
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  get_it: ^8.0.2
  go_router: ^14.0.2
  flutter_svg: ^2.0.10+1
  flutter_staggered_animations: ^1.1.1
  flutter_cache_manager: ^3.3.1
  fluttertoast: ^8.2.4
  just_audio: ^0.9.42
  audio_session: ^0.1.21
  shared_preferences: ^2.3.3
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  mobx_codegen: ^2.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/babycards/cards/icons/
    - assets/babycards/cards/images/
    - assets/babycards/cards/audios/ru/
    - assets/babycards/cards/raws/default/
    - assets/babycards/cards/raws/ru/
    - assets/babycards/categories/icons/
    - assets/babycards/categories/audios/ru/
    - assets/database/
    - assets/app/audios/
    - assets/app/icons/
    - assets/app/images/
    - assets/games/audios/answers/ru/
    - assets/games/audios/questions/ru/

flutter_launcher_icons:
  android: true
  image_path_android: 'assets/app/icons/icon_app.png'
  ios: true
  image_path_ios: 'assets/app/icons/icon_app.png'
  remove_alpha_ios: true
  min_sdk_android: 21
  adaptive_icon_background: '#00B2FF'

