name: busycards
description: A new Flutter project.
publish_to: 'none'
version: 2.0.8+28

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3
  intl: ^0.18.1
  path: ^1.9.0
  provider: ^6.1.2
  assets_audio_player: ^3.1.1
  url_launcher: ^6.2.6
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  get_it: ^7.7.0
  go_router: ^14.0.2
  flutter_svg: ^2.0.10+1
  flutter_staggered_animations: ^1.1.1
  flutter_cache_manager: ^3.3.1
  fluttertoast: ^8.2.4
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.9
  mobx_codegen: ^2.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/babycards/cards/icons/
    - assets/babycards/cards/images/
    - assets/babycards/cards/audios/ru/
    - assets/babycards/cards/raws/default/
    - assets/babycards/cards/raws/ru/
    - assets/babycards/categories/icons/
    - assets/babycards/categories/audios/ru/
    - assets/database/
    - assets/app/images/
    - assets/app/icons/
    - assets/games/audios/answers/ru/
    - assets/games/audios/questions/ru/

